name: CodeQL Analysis 

on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract CodeQL CLI bundle
        run: |
          wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
          tar -xvzf codeql-bundle-linux64.tar.gz

      - name: Add CodeQL CLI to PATH
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo "::add-path::$(pwd)/codeql:$PATH"

      - name: Create CodeQL database
        run: |
          codeql database create my-database --language=java --source-root="./" --command="mvn clean compile"

      - name: Run custom queries
        run: |
          codeql query run './custom-queries/filenames.ql' --database=my-database --output=filenames-results.bqrs

      - name: Transform .bqrs to JSON with CodeQL CLI
        run: |
          codeql bqrs decode --format=json --output=filenames-results.json filenames-results.bqrs

      - name: Upload filename results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: filenames-results.json
